"""add sar burn perimeter and building damage geojson columns

Revision ID: 4db8bdcf5248
Revises: db45e35d3d2b
Create Date: 2026-07-31 12:40:38.497949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db8bdcf5248'
down_revision: Union[str, Sequence[str], None] = 'db45e35d3d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fires', sa.Column('acquisition_burn_perimeter', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('fires', sa.Column('acquisition_building_damage', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fires', 'acquisition_building_damage')
    op.drop_column('fires', 'acquisition_burn_perimeter')
    # ### end Alembic commands ###
