"""add SAR acquisition workflow fields to fires

Revision ID: 5ccba1386d1d
Revises: ddc2afa3e14d
Create Date: 2026-07-29 20:02:40.972958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ccba1386d1d'
down_revision: Union[str, Sequence[str], None] = 'ddc2afa3e14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fires', sa.Column('acquisition_status', sa.String(), nullable=True))
    op.add_column('fires', sa.Column('acquisition_before_scene', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fires', sa.Column('acquisition_after_scene', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fires', sa.Column('acquisition_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fires', 'acquisition_confirmed_at')
    op.drop_column('fires', 'acquisition_after_scene')
    op.drop_column('fires', 'acquisition_before_scene')
    op.drop_column('fires', 'acquisition_status')
    # ### end Alembic commands ###
