"""add fire cause, containment percent, complexity level

Revision ID: 686bd121c4f5
Revises: ca4f0c1ac9bd
Create Date: 2026-07-29 16:29:26.511115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686bd121c4f5'
down_revision: Union[str, Sequence[str], None] = 'ca4f0c1ac9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fires', sa.Column('percent_contained', sa.Integer(), nullable=True))
    op.add_column('fires', sa.Column('fire_cause', sa.String(), nullable=True))
    op.add_column('fires', sa.Column('complexity_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fires', 'complexity_level')
    op.drop_column('fires', 'fire_cause')
    op.drop_column('fires', 'percent_contained')
    # ### end Alembic commands ###
