"""initial schema: fires, building_cache, exposure_stats, ingestion_status

Revision ID: ca4f0c1ac9bd
Revises: 
Create Date: 2026-07-28 16:08:41.706140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4f0c1ac9bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fires',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('perimeter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acres', sa.Numeric(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_cache',
    sa.Column('fire_id', sa.String(), nullable=False),
    sa.Column('buildings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fire_id'], ['fires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fire_id')
    )
    op.create_table('exposure_stats',
    sa.Column('fire_id', sa.String(), nullable=False),
    sa.Column('buffer_meters', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('building_count', sa.Integer(), nullable=True),
    sa.Column('population_est', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['fire_id'], ['fires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fire_id', 'buffer_meters', 'computed_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exposure_stats')
    op.drop_table('building_cache')
    op.drop_table('ingestion_status')
    op.drop_table('fires')
    # ### end Alembic commands ###
