"""add sar compute dispatch tracking fields

Revision ID: db45e35d3d2b
Revises: 68638b5b0811
Create Date: 2026-07-31 07:09:17.076938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db45e35d3d2b'
down_revision: Union[str, Sequence[str], None] = '68638b5b0811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fires', sa.Column('acquisition_batch_job_id', sa.String(), nullable=True))
    op.add_column('fires', sa.Column('acquisition_result', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('fires', sa.Column('acquisition_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fires', 'acquisition_error')
    op.drop_column('fires', 'acquisition_result')
    op.drop_column('fires', 'acquisition_batch_job_id')
    # ### end Alembic commands ###
