"""add fire state field

Revision ID: ddc2afa3e14d
Revises: 686bd121c4f5
Create Date: 2026-07-29 17:01:19.716758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc2afa3e14d'
down_revision: Union[str, Sequence[str], None] = '686bd121c4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fires', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fires', 'state')
    # ### end Alembic commands ###
